wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709648118.509365
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      2:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 7
      - 23
      4: 3.8.18
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: val loss1
      5: 1
      6:
      - 1
    - 1: val loss2
      5: 1
      6:
      - 1
    - 1: val loss
      5: 1
      6:
      - 1
    - 1: val_PSNR
      5: 1
      6:
      - 1
    - 1: val_SSIM
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train loss1
      5: 1
      6:
      - 1
    - 1: train loss2
      5: 1
      6:
      - 1
    - 1: train loss
      5: 1
      6:
      - 1
model_name:
  desc: null
  value: UNet-DAS
base_dir:
  desc: null
  value: D:\HISLab\DATASET\StripSkullCT_Simulation
mixed_signal_dir:
  desc: null
  value: D:\HISLab\DATASET\StripSkullCT_Simulation\mixed_signal
direct_signal_dir:
  desc: null
  value: D:\HISLab\DATASET\StripSkullCT_Simulation\direct_signal
target_dir:
  desc: null
  value: D:\HISLab\DATASET\StripSkullCT_Simulation\target
sensor_mask_dir:
  desc: null
  value: D:\HISLab\DATASET\StripSkullCT_Simulation\sensor_mask_idx.mat
save_dir:
  desc: null
  value: D:\HISLab\DATASET\StripSkullCT_Simulation\RESULT
n_classes:
  desc: null
  value: 1
channels:
  desc: null
  value: 50
dt:
  desc: null
  value: 2.0e-07
train_size:
  desc: null
  value: 0.8
val_size:
  desc: null
  value: 0.1
max_epochs:
  desc: null
  value: 300
min_epochs:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 32
num_workers:
  desc: null
  value: 2
seed:
  desc: null
  value: 1121
lr1:
  desc: null
  value: 0.001
lr2:
  desc: null
  value: 0.0001
loss:
  desc: null
  value: mse
