base_dir: .\example
batch_size: 12
channels: 50
direct_signal_dir: .\example\direct_signal
dt: 2.0e-07
loss: mse
lr1: 0.001
lr2: 0.0001
max_epochs: 10
min_epochs: 5
mixed_signal_dir: .\example\mixed_signal
model_name: UNet-DAS
n_classes: 1
num_workers: 2
save_dir: .\example\RESULT
seed: 1121
sensor_mask_dir: .\example\sensor_mask_idx.mat
target_dir: .\example\target
train_size: 0.8
val_size: 0.1
