base_dir: D:\HISLab\DATASET\StripSkullCT_Simulation
batch_size: 32
channels: 50
direct_signal_dir: D:\HISLab\DATASET\StripSkullCT_Simulation\direct_signal
dt: 2.0e-07
loss: mse
lr1: 0.0001
lr2: 0.0001
max_epochs: 3
min_epochs: 3
mixed_signal_dir: D:\HISLab\DATASET\StripSkullCT_Simulation\mixed_signal
model_name: UNet-DAS
n_classes: 1
num_workers: 4
save_dir: D:\HISLab\DATASET\StripSkullCT_Simulation\RESULT
seed: 1121
sensor_mask_dir: D:\HISLab\DATASET\StripSkullCT_Simulation\sensor_mask_idx.mat
target_dir: D:\HISLab\DATASET\StripSkullCT_Simulation\target
train_size: 0.8
val_size: 0.1
