model_name: UNet-DAS
base_dir: D:\HISLab\DATASET\StripSkullCT_Simulation
mixed_signal_dir: D:\HISLab\DATASET\StripSkullCT_Simulation\mixed_signal
direct_signal_dir: D:\HISLab\DATASET\StripSkullCT_Simulation\direct_signal
target_dir: D:\HISLab\DATASET\StripSkullCT_Simulation\target
sensor_mask_dir: D:\HISLab\DATASET\StripSkullCT_Simulation\sensor_mask_idx.mat
save_dir: D:\HISLab\DATASET\StripSkullCT_Simulation\RESULT
n_classes: 1
channels: 25
dt: 2.0e-07
train_size: 0.9
val_size: 0.1
max_epochs: 300
batch_size: 2
num_workers: 15
seed: 1121
lr: 0.001
loss: mse
